import { 
  collection, 
  addDoc, 
  serverTimestamp 
} from "firebase/firestore";
import { db } from "./firebase";

export const initializeSupportPortalData = async () => {
  console.log("Initializing support portal data...");

  // Initialize sample system alerts
  const alerts = [
    {
      title: "Welcome to Support Portal",
      description: "This is a sample alert to demonstrate the system alerts functionality.",
      severity: "info",
      affectedServices: ["frontend"],
      resolved: false,
      escalationLevel: 0,
      autoGenerated: false,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    }
  ];

  // Initialize sample client environments
  const environments = [
    {
      clientName: "Demo Fitness Studio",
      environment: "production",
      status: "active",
      lastLogin: new Date(),
      subscription: "premium",
      clientCount: 50,
      dataUsage: 1.2,
      issues: 0,
      supportTier: "priority",
      healthMetrics: {
        uptime: 99.9,
        responseTime: 200,
        errorRate: 0.1,
        lastHealthCheck: new Date()
      },
      recentActivity: [
        {
          type: 'login',
          timestamp: new Date(),
          description: 'Admin login to dashboard'
        }
      ]
    }
  ];

  try {
    // Add sample alerts
    for (const alert of alerts) {
      await addDoc(collection(db, "systemAlerts"), alert);
    }
    console.log("✓ Sample alerts created");

    // Add sample environments
    for (const env of environments) {
      await addDoc(collection(db, "clientEnvironments"), env);
    }
    console.log("✓ Sample client environments created");

    console.log("Support portal data initialization complete!");
  } catch (error) {
    console.error("Error initializing support portal data:", error);
  }
};

// Function to generate a test error log
export const generateTestErrorLog = async () => {
  try {
    await addDoc(collection(db, "errorLogs"), {
      timestamp: serverTimestamp(),
      level: "info",
      message: "Test error log from support portal initialization",
      service: "support-portal",
      userId: "system",
      sessionId: "init",
      metadata: {
        test: true,
        purpose: "initialization"
      }
    });
    console.log("✓ Test error log created");
  } catch (error) {
    console.error("Error creating test log:", error);
  }
}; 