import { Client, Session, Payment } from "./types";

// Centralized mock data for the application
export const mockClients: Client[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "(555) 123-4567",
    dateJoined: "2024-01-15",
    fitnessLevel: "intermediate",
    goals: "Weight loss and strength building",
    notes:
      "Prefers morning sessions. Has knee issues - avoid high impact exercises.",
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike.chen@email.com",
    phone: "(555) 234-5678",
    dateJoined: "2024-02-03",
    fitnessLevel: "beginner",
    goals: "Build muscle mass and improve endurance",
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily.davis@email.com",
    phone: "(555) 345-6789",
    dateJoined: "2024-01-28",
    fitnessLevel: "advanced",
    goals: "Marathon training and performance optimization",
  },
  {
    id: "4",
    name: "James Wilson",
    email: "james.wilson@email.com",
    phone: "(555) 456-7890",
    dateJoined: "2024-02-10",
    fitnessLevel: "intermediate",
    goals: "Functional fitness and injury prevention",
  },
  {
    id: "5",
    name: "Alex Thompson",
    email: "alex.thompson@email.com",
    phone: "(555) 567-8901",
    dateJoined: "2025-01-18",
    fitnessLevel: "beginner",
    goals: "General fitness and health improvement",
  },
  {
    id: "6",
    name: "Maria Rodriguez",
    email: "maria.rodriguez@email.com",
    phone: "(555) 678-9012",
    dateJoined: "2025-01-13",
    fitnessLevel: "intermediate",
    goals: "Strength training and flexibility",
  },
  {
    id: "7",
    name: "David Kim",
    email: "david.kim@email.com",
    phone: "(555) 789-0123",
    dateJoined: "2025-01-06",
    fitnessLevel: "advanced",
    goals: "Competition preparation and peak performance",
  },
];

export const mockSessions: Session[] = [
  // Past completed sessions
  {
    id: "1",
    clientId: "1",
    date: "2025-01-15",
    startTime: "09:00",
    endTime: "10:00",
    type: "personal-training",
    status: "completed",
    notes: "Great session, client showed improvement in form",
    cost: 75,
  },
  {
    id: "2",
    clientId: "2",
    date: "2025-01-15",
    startTime: "10:30",
    endTime: "11:30",
    type: "assessment",
    status: "completed",
    notes: "Initial fitness assessment completed",
    cost: 50,
  },
  {
    id: "3",
    clientId: "3",
    date: "2025-01-16",
    startTime: "14:00",
    endTime: "15:00",
    type: "personal-training",
    status: "completed",
    cost: 75,
  },
  {
    id: "4",
    clientId: "4",
    date: "2025-01-17",
    startTime: "15:30",
    endTime: "16:30",
    type: "consultation",
    status: "completed",
    cost: 60,
  },

  // Upcoming scheduled sessions
  {
    id: "5",
    clientId: "1",
    date: "2025-01-22",
    startTime: "09:00",
    endTime: "10:00",
    type: "personal-training",
    status: "scheduled",
    cost: 75,
  },
  {
    id: "6",
    clientId: "2",
    date: "2025-01-22",
    startTime: "11:00",
    endTime: "12:00",
    type: "personal-training",
    status: "scheduled",
    cost: 75,
  },
  {
    id: "7",
    clientId: "3",
    date: "2025-01-23",
    startTime: "14:00",
    endTime: "15:00",
    type: "personal-training",
    status: "scheduled",
    cost: 75,
  },
  {
    id: "8",
    clientId: "4",
    date: "2025-01-23",
    startTime: "16:00",
    endTime: "17:00",
    type: "consultation",
    status: "scheduled",
    cost: 60,
  },
  {
    id: "9",
    clientId: "5",
    date: "2025-01-24",
    startTime: "10:00",
    endTime: "11:00",
    type: "assessment",
    status: "scheduled",
    cost: 50,
  },
  {
    id: "10",
    clientId: "6",
    date: "2025-01-24",
    startTime: "13:00",
    endTime: "14:00",
    type: "personal-training",
    status: "scheduled",
    cost: 75,
  },
  {
    id: "11",
    clientId: "7",
    date: "2025-01-25",
    startTime: "09:00",
    endTime: "10:00",
    type: "personal-training",
    status: "scheduled",
    cost: 75,
  },
  {
    id: "12",
    clientId: "1",
    date: "2025-01-25",
    startTime: "15:00",
    endTime: "16:00",
    type: "personal-training",
    status: "scheduled",
    cost: 75,
  },

  // Some cancelled sessions
  {
    id: "13",
    clientId: "1",
    date: "2025-01-20",
    startTime: "10:00",
    endTime: "11:00",
    type: "personal-training",
    status: "cancelled",
    notes: "Client cancelled via portal: Schedule conflict - have to work late",
    cost: 75,
    cancelledBy: "client",
    cancelledAt: "2025-01-17T10:30:00Z",
  },
  {
    id: "14",
    clientId: "2",
    date: "2025-01-21",
    startTime: "14:00",
    endTime: "15:00",
    type: "personal-training",
    status: "cancelled",
    notes: "Trainer cancelled due to illness",
    cost: 75,
    cancelledBy: "trainer",
    cancelledAt: "2025-01-18T09:00:00Z",
  },
];

export const mockPayments: Payment[] = [
  // Completed payments
  {
    id: "1",
    clientId: "1",
    sessionId: "1",
    amount: 75,
    date: "2025-01-15",
    method: "card",
    status: "completed",
    description: "Personal Training Session",
  },
  {
    id: "2",
    clientId: "2",
    sessionId: "2",
    amount: 50,
    date: "2025-01-15",
    method: "cash",
    status: "completed",
    description: "Fitness Assessment",
  },
  {
    id: "3",
    clientId: "3",
    sessionId: "3",
    amount: 75,
    date: "2025-01-16",
    method: "bank-transfer",
    status: "completed",
    description: "Personal Training Session",
  },
  {
    id: "4",
    clientId: "4",
    sessionId: "4",
    amount: 60,
    date: "2025-01-17",
    method: "venmo",
    status: "completed",
    description: "Consultation",
  },
  {
    id: "5",
    clientId: "1",
    amount: 225,
    date: "2025-01-01",
    method: "card",
    status: "completed",
    description: "Monthly Package (3 sessions)",
  },
  {
    id: "6",
    clientId: "2",
    amount: 150,
    date: "2025-01-03",
    method: "bank-transfer",
    status: "completed",
    description: "Bi-weekly Package (2 sessions)",
  },
  {
    id: "7",
    clientId: "3",
    amount: 300,
    date: "2025-01-05",
    method: "card",
    status: "completed",
    description: "Monthly Package (4 sessions)",
  },

  // Pending payments (unpaid invoices)
  {
    id: "8",
    clientId: "4",
    amount: 180,
    date: "2025-01-10",
    method: "bank-transfer",
    status: "pending",
    description: "Monthly Package (3 sessions)",
  },
  {
    id: "9",
    clientId: "5",
    amount: 50,
    date: "2025-01-18",
    method: "cash",
    status: "pending",
    description: "Initial Assessment",
  },
  {
    id: "10",
    clientId: "6",
    amount: 150,
    date: "2025-01-13",
    method: "venmo",
    status: "pending",
    description: "Bi-weekly Package (2 sessions)",
  },

  // Failed payment
  {
    id: "11",
    clientId: "7",
    amount: 75,
    date: "2025-01-19",
    method: "card",
    status: "failed",
    description: "Personal Training Session",
  },
];

// Helper function to get client name by ID
export const getClientName = (clientId: string): string => {
  const client = mockClients.find((c) => c.id === clientId);
  return client ? client.name : "Unknown Client";
};
